# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pierre Boucher's Online Repository
email: pob3541@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My central online repository for storing the various projects I have worked on over the years.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: PierreOBoucher
github_username:  pob3541

# Build settings
markdown: kramdown
theme: minima
